apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: rag-demo-i537578 # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "RAG Demo"
    scenarios.ai.sap.com/name: "rag-demo"
    executables.ai.sap.com/description: "RAG Demo"
    executables.ai.sap.com/name: "rag-demo-policy"
  labels:
    scenarios.ai.sap.com/id: "rag-demo-id"
    ai.sap.com/version: "1.6"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-anupriyagurusamy
        minReplicas: 1
        maxReplicas: 5    # how much to scale
        containers:
        - name: kserve-container
          image: "docker.io/anupriyagurusamy/rag-demo:07" # Your docker image name
          ports:
            - containerPort: 8080
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting" && gunicorn --chdir /app/src/ main:app -b "0.0.0.0:8080" --access-logfile '-' -t 0
